import "./globals.css";
import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const josefinFont = Josefin_Sans({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin-ext"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={josefinFont.className}>
        <Toaster />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
